---
title: "Temporal Trend"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)
```


```{r}
collision_df = read_csv("./data/collision_df.csv")

shiny_df = collision_df |> 
  select(collision_id, year, month, day, day_of_week, hour, num_casualty, severity, vehicle_type, latitude, longitude) |> 
  distinct(collision_id, .keep_all = TRUE) |> 
  mutate(
    # Create date objects and factors for plotting
    date = make_date(year, month, day),
    month_label = month(date, label = TRUE, abbr = TRUE),
    day_of_week = factor(day_of_week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
    )


```


Column {.sidebar}
=====================================


```{r}
Years = shiny_df |> distinct(year) |> pull(year)

selectInput(
  inputId = "year_choice",
  label = h2("Select Year"),
  choices = Years,
  selected = 2024
)
```

```{r}
radioButtons(
  inputId = "severity_choice",
  label = h2("Severity Level"),
  choices = c(
    "All (All Incidents)" = "all",
    "Minor (Non-Injury)" = "minor",
    "Medium (Injury only)" = "medium", 
    "Severe (Death Involved)" = "severe"
  ),
  selected = "medium"
)
```

Collision Incidence (Bar)
==========================================================================  

### Monthly Trend

```{r}
renderPlotly({
  plot_df = shiny_df |> 
    filter(year == input[["year_choice"]])
  
  if (input[["severity_choice"]] != "all") {
    plot_df = plot_df |> filter(severity == input[["severity_choice"]])
  }
  
  plot_df = 
    plot_df |> 
    group_by(month_label) |> 
    summarise(
      total_incidents = n(),
      days_in_month = n_distinct(date),
      avg_daily = total_incidents / days_in_month,
      .groups = "drop"
    )
  
  plot_df |> 
    plot_ly(
      x = ~month_label, 
      y = ~avg_daily, 
      color = ~month_label,
      colors = "viridis",
      type = "bar"
    ) |> 
    layout(
      title = paste0("Total Collisions by Month in ",input[["year_choice"]]),
      xaxis = list(title = "Month"),
      yaxis = list(title = "Avg Incidents per Day")
    )
})
```

### Weekly Trend

```{r}
renderPlotly({
  plot_df = shiny_df |> 
    filter(year == input[["year_choice"]])
  
  n_weeks = n_distinct(week(pull(plot_df, date)))
  
  if (input[["severity_choice"]] != "all") {
    plot_df = plot_df |> filter(severity == input[["severity_choice"]])
  }
  
  
  plot_df |> 
    count(day_of_week) |>
    mutate(avg_incidents = n / n_weeks) |> 
    plot_ly(
      x = ~day_of_week, 
      y = ~avg_incidents, 
      color = ~day_of_week,
      colors = "viridis",
      type = "bar"
    ) |> 
    layout(
      title = paste0("Average Collisions by Day of Week in ", input[["year_choice"]]),
      xaxis = list(title = "Day of Week"),
      yaxis = list(title = "Avg Incidents per Day")
    )
})
```

### Hourly Trend

```{r}
renderPlotly({
  plot_df = shiny_df |> 
    filter(year == input[["year_choice"]])
  
  n_days = n_distinct(pull(plot_df, date))
    
  if (input[["severity_choice"]] != "all") {
    plot_df = plot_df |> filter(severity == input[["severity_choice"]])
  }
  
  plot_df |> 
    count(hour) |>
    mutate(avg_incidents = n / n_days) |> 
    plot_ly(
      x = ~hour, 
      y = ~avg_incidents, 
      color = ~hour,
      colors = "viridis",
      type = "bar"
    ) |> 
    layout(
      title = paste0("Average Collisions by Hour of Day in ", input[["year_choice"]]),
      xaxis = list(title = "Hour (0-23)", dtick = 2),
      yaxis = list(title = "Avg Incidents")
    )
})
```

Casualty Persons (Violin)
==========================================================================  
### Monthly Casualty Distribution


```{r}
renderPlotly({
  plot_df <- shiny_df |> 
    filter(year == input[["year_choice"]], num_casualty > 0)
  
  if (input[["severity_choice"]] == "medium") {
    plot_df <- plot_df |> filter(severity == "medium")
  } else if (input[["severity_choice"]] == "severe") {
    plot_df <- plot_df |> filter(severity == "severe")
  } 

  plot_df |>
    plot_ly(
      x = ~month_label,
      y = ~num_casualty,
      type = 'violin',
      marker = list(size = 5, opacity = 0.6),
      color = ~month_label,
      colors = "viridis"
    ) |>
    layout(
      title = paste0("Casualty Distribution by Month in ", input[["year_choice"]]),
      xaxis = list(title = "Month"),
      yaxis = list(title = "Number of Casualty")
    )
})
```

### Weekly Casualty Distribution

  
```{r}
renderPlotly({
  plot_df <- shiny_df |> 
    filter(year == input[["year_choice"]], num_casualty > 0)
  
  if (input[["severity_choice"]] == "medium") {
    plot_df <- plot_df |> filter(severity == "medium")
  } else if (input[["severity_choice"]] == "severe") {
    plot_df <- plot_df |> filter(severity == "severe")
  } 
  
  plot_df |>
    plot_ly(
      x = ~day_of_week,
      y = ~num_casualty,
      type = 'violin',
      boxpoints = 'all',
      marker = list(size = 5, opacity = 0.6),
      color = ~day_of_week,
      colors = "viridis"
    ) |>
    layout(
      title = paste0("Casualty Distribution by Day of Week in ", input[["year_choice"]]),
      xaxis = list(title = "Day of Week"),
      yaxis = list(title = "Number of Casualty")
    )
})
```

### Hourly Casualty Distribution

```{r}
renderPlotly({

  plot_df <- shiny_df |> 
    filter(year == input[["year_choice"]], num_casualty > 0)
  
  if (input[["severity_choice"]] == "medium") {
    plot_df <- plot_df |> filter(severity == "medium")
  } else if (input[["severity_choice"]] == "severe") {
    plot_df <- plot_df |> filter(severity == "severe")
  } 

  # 3. Plot Boxplot with Jitter
  plot_df |>
    plot_ly(
      x = ~hour,
      y = ~num_casualty,
      type = 'box',
      marker = list(size = 3, opacity = 0.6),
      color = ~hour, 
      colors = "viridis"
    ) |>
    layout(
      title = paste0("Casualty Distribution by Hour of Day in ",  input[["year_choice"]]),
      xaxis = list(title = "Hour (0-23)", dtick = 2),
      yaxis = list(title = "Number of Casualty")
    )
})
```

